os:
  - linux
services:
  - docker
language: java
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.m2
before_install:
  - java -version
  - docker pull couchbase
  - docker run -d --name db -p 8091-8094:8091-8094 -p 11210:11210 couchbase
  - sleep 60
  - export COUCHBASEHOST=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' "db")
  - curl -v -X POST http://$COUCHBASEHOST:8091/settings/web -d port=8091 -d username=Administrator -d password=password
  - curl -X POST -u Administrator:password -d name=default -d ramQuotaMB=256 -d authType=sasl -d replicaNumber=0 http://$COUCHBASEHOST:8091/pools/default/buckets
script:
  - ./mvnw clean
  - ./mvnw test -DCOUCHBASEHOST=$COUCHBASEHOST
  - ./mvnw package -Pprod -DskipTests
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
after_success:
  - mvn clean cobertura:cobertura coveralls:report
