spring:
    application:
        name: CronitSchedulerRepository
    jackson:
        date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
        serialization:
            write-dates-as-timestamps: false
    profiles:
        # The commented value for `active` can be replaced with valid Spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: #spring.profiles.active#
couchbase:
    hosts:
      - 127.0.0.1
      - localhost
    bucket: default
    password:
server:
    port: 8080

security:
    basic:
        enabled: false
application:
    hash-salt: salt
management:
  security:
    enabled: false